IMG = "https://static.prod-images.emergentagent.com/jobs/7ee9dc22-104f-4f5f-bce4-68271cc60488/images/"

PRODUCTS = [
    {
        "id": "sac-lune-nacre",
        "name": "Le Sac Lune Nacre",
        "subtitle": "Sac rigide en perles blanches tressées",
        "price": 55000,
        "category": "sacs",
        "accent": "Blanc pur",
        "tag": "Bestseller",
        "weaving_hours": 16,
        "dimensions": "20 × 14 × 6 cm",
        "images": [IMG + "46cb48231813f0acda019e8e5e4356b4088a4400185d9ab3649fcedbbc567ab0.jpeg"],
        "description": "Forme structurée en demi-lune, intégralement tissée à la main avec plus de 1 200 perles nacrées blanches. Anse perlée renforcée et intérieur doublé.",
        "featured": True,
    },
    {
        "id": "sac-nacre-classique",
        "name": "Le Sac Nacre Classique",
        "subtitle": "Sac à main & bracelet assorti",
        "price": 48000,
        "category": "sacs",
        "accent": "Blanc pur",
        "tag": "Duo",
        "weaving_hours": 14,
        "dimensions": "19 × 13 × 6 cm",
        "images": [IMG + "948ae007bf90f1cccd44d63de2610a179d9d7fd504a584b2a390c834a7a1bdf1.jpeg"],
        "description": "Le classique de l'atelier, livré avec son bracelet en perles assorti. Un ensemble lumineux pour les cérémonies et les grandes occasions.",
        "featured": True,
    },
    {
        "id": "cabas-fleur-de-soleil",
        "name": "Le Cabas Fleur de Soleil",
        "subtitle": "Perles blanches et fleurs orange ambré",
        "price": 68000,
        "category": "sacs",
        "accent": "Fleur orange",
        "tag": "Édition limitée",
        "weaving_hours": 22,
        "dimensions": "24 × 14 × 9 cm",
        "images": [IMG + "638c5bb9c6b1c9f2320fb89647f1941b48f217bba82e11ac795513904763fac3.jpeg"],
        "description": "Sublimé par de délicates fleurs en perles orange insérées dans un maillage blanc. Un hommage aux soleils couchants de la côte ouest-africaine.",
        "featured": True,
    },
    {
        "id": "panier-soleil-structure",
        "name": "Le Panier Soleil Structuré",
        "subtitle": "Cabas rectangulaire à motifs floraux",
        "price": 72000,
        "category": "sacs",
        "accent": "Fleur orange",
        "tag": "Nouveauté",
        "weaving_hours": 26,
        "dimensions": "22 × 18 × 8 cm",
        "images": [IMG + "6fb44d546c549ddb989ca3038d6b535177b7e6eda7b6cbf12e5d215a4ce25389.jpeg"],
        "description": "Silhouette architecturale, neuf fleurs orange tissées en relief sur une trame de perles blanches. Se porte à la main, tête haute.",
        "featured": True,
    },
    {
        "id": "panier-fleur-amethyste",
        "name": "Le Panier Fleur d'Améthyste",
        "subtitle": "Cabas carré à fleur violette",
        "price": 62000,
        "category": "sacs",
        "accent": "Fleur violette",
        "tag": "Coup de cœur",
        "weaving_hours": 18,
        "dimensions": "18 × 16 × 9 cm",
        "images": [IMG + "d483f02574a8bd6c9b24c025cad33c6617fc51b1ae1c176f97e8ab23d3ca16b1.jpeg"],
        "description": "Un panier au tissage ajouré, illuminé d'une fleur violette profonde. Conçu pour accompagner vos tenues de célébration.",
        "featured": True,
    },
    {
        "id": "collection-mini-trio",
        "name": "La Collection Mini Trio",
        "subtitle": "Trois mini-sacs : rond, anse ronde, rayé",
        "price": 95000,
        "category": "minis",
        "accent": "Blanc, bleu & gris",
        "tag": "Coffret",
        "weaving_hours": 30,
        "dimensions": "3 pièces · 12 à 15 cm",
        "images": [IMG + "3162899abd160da05fb509fe34b1c229746b7566748d4ebef2af7e3423814f43.jpeg"],
        "description": "Un coffret de trois mini-sacs : la pochette ronde à chaîne et fleur bleue, le mini-sac à anse ronde et le sac rayé aux perles marbrées grises.",
        "featured": False,
    },
    {
        "id": "parure-perles-blanches",
        "name": "La Parure Perles Blanches",
        "subtitle": "Collier double rang & boucles d'oreilles",
        "price": 35000,
        "category": "bijoux",
        "accent": "Blanc pur",
        "tag": "Essentiel",
        "weaving_hours": 8,
        "dimensions": "Collier 48 cm · Boucles 5 cm",
        "images": [IMG + "9f479b1f426704ec3959febadbe5f31f0d208ea76b3585c35a18461aa8ea1c11.jpeg"],
        "description": "Un collier double rang aux perles graduées, accompagné de ses boucles d'oreilles pendantes. Parure de mariée intemporelle.",
        "featured": True,
    },
    {
        "id": "parure-nacre-bague",
        "name": "La Parure Nacre & Bague",
        "subtitle": "Collier, boucles d'oreilles et bague",
        "price": 42000,
        "category": "bijoux",
        "accent": "Blanc pur",
        "tag": None,
        "weaving_hours": 10,
        "dimensions": "Collier 50 cm · Bague ajustable",
        "images": [IMG + "6d9b5a4bf8e02572a0ce17141868ead5d8303ba81184d4615a61c7354f9762b7.jpeg"],
        "description": "Ensemble complet trois pièces : collier double rang, boucles d'oreilles perles et bague tissée assortie.",
        "featured": False,
    },
    {
        "id": "parure-ambre",
        "name": "La Parure Ambre",
        "subtitle": "Fleurs de cristal ambré & perles transparentes",
        "price": 45000,
        "category": "bijoux",
        "accent": "Ambre",
        "tag": "Nouveauté",
        "weaving_hours": 12,
        "dimensions": "Collier 46 cm · Boucles 6 cm",
        "images": [
            IMG + "85bcddc3e7e29cc572b81600bcbe7c945eda731b37605ed8314ff3aec5ca8d36.jpeg",
            IMG + "84b8e25e1f496e0775005a7db0dde27dd7a11a3e05c54e45b9a9f534c0c0ba65.jpeg",
        ],
        "description": "Des fleurs en cristal facetté couleur ambre, reliées par des perles transparentes. Collier et boucles d'oreilles à dormeuses argentées.",
        "featured": True,
    },
]
